stages:
  - build
  - qa

variables:
  MYSQL_ROOT_PASSWORD: mypass

services:
  - mariadb:10.5.9

build:
  stage: build
  image: lvo9/demo
  variables:
    DATABASE_URL: 'mysql://root:mypass@mariadb:3306/mydb?serverVersion=mariadb-10.5.9'
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor/
      - bin/.phpunit
  script:
    - composer install
    - bin/console doctrine:database:create
    - bin/console doctrine:migrations:migrate -n
    - bin/phpunit install
  artifacts:
    paths:
      - vendor

test:
  stage: qa
  image: lvo9/demo
  script: bin/phpunit

cs:
  stage: qa
  image: lvo9/demo
  script:
    - vendor/bin/php-cs-fixer fix --dry-run
    - php -d memory_limit=-1 vendor/bin/phpstan analyse src