name: CI

on: push

env:
  DATABASE_URL: 'mysql://root:mypass@127.0.0.1:3306/mydb?serverVersion=mariadb-10.5.9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-vendor
        with:
          path: |
            vendor/
            bin/.phpunit/
          key: vendor-${{ hashFiles('composer.lock') }}
      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mysql
          tools: composer:v2
      - name: Composer install
        run: composer install
        if: steps.cache-vendor.outputs.cache-hit != 'true'
      - name: PHPUnit install
        run: bin/phpunit install

  cs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-vendor
        with:
          path: |
              vendor/
              bin/.phpunit/
          key: vendor-${{ hashFiles('composer.lock') }}

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mysql
          tools: composer:v2
      - run: composer install
      - run: bin/phpunit install
      - run: php vendor/bin/php-cs-fixer fix --dry-run src
      - run: php -d memory_limit=-1 vendor/bin/phpstan analyse src

  test:
    needs: [build]
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb:10.5.9
        env:
          MYSQL_ROOT_PASSWORD: mypass
        ports:
          - 3306:3306/tcp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-vendor
        with:
          path: |
            vendor/
            bin/.phpunit/
          key: vendor-${{ hashFiles('composer.lock') }}
      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mysql
          tools: composer:v2
      - run: composer install
      - run: bin/phpunit install
      - run: bin/console doctrine:database:create
      - run: bin/console doctrine:migrations:migrate -n
      - run: bin/console doctrine:fixtures:load -n
      - run: php -d memory_limit=-1 bin/phpunit -v
